import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useRouter } from 'next/router'

export default function Home({blogs}) {
  // console.log(blogs)
  const router=useRouter()
  const handlepage=(id)=>{
    router.push(`${id}`)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'20px'}}>
          {
            blogs.map((el)=>(
              <div key={el.title} style={{border:'1px solid grey',textAlign:'center',padding:'15px',borderRadius:'8px'}} onClick={()=>handlepage(el.id)}>
                <h4>{el.title}</h4>
              </div>
            ))
          }
      </div>
    </div>
  )
}


export async function getServerSideProps() {
  let  res=await fetch(`http://localhost:4000/blogs`)
  let data=await res.json()
  return {
    props: {
      blogs:data
    },
  }
} 